### ISSUE TITLE
Lost Connection

### ISSUE THREAD

**Issue by Debranis** [bitfocus/companion-module-vimeo-livestreamstudio6#6]
Every time I start a new session I have to start the Companion GUI, disable the LiveStream connection, and reenable the connection for it to work.  I can obviously work around it, but it is quite annoying to lose the connection every time I start and sometimes during the middle of a session.

**Comment by ChgoChad** [comment]
> Every time I start a new session I have to start the Companion GUI, disable the LiveStream connection, and reenable the connection for it to work. I can obviously work around it, but it is quite annoying to lose the connection every time I start and sometimes during the middle of a session.

Hello there - My apologies for the delay in responding, my notifications for this repo were turned off inadvertently.  I'm sorry that you are having connection issues with the module. Unfortunately, by the way Companion is designed when you close down Companion the module shuts down as well and therefore will break the connection. The connection will be re-established when you restart Companion and re-enable the module.  

**One way around this would be the following:** 

1.  In Companion create a New **Trigger**  (Under the Triggers tab at the top)
2.  Set the **Event** to be `[Startup]` with a few second delay (say 5000ms - which is 5 seconds)
3.  Set the **Condition** to `[internal: Connection matches specified status]`, and set the **Connection** to your instance of Livestream Studio and the connection **status** to be `[Disabled]`.
4.  Finally set the **Action** to `[internal: Enable or disable connection]`, and set the **Connection** to your instance of Livestream Studio and **Enable** to `[Yes]`

This trigger will run each time you start Companion and will auto-enable the Livestream Studio module a few seconds after Companion has finished loading, but it will only enable the module if it finds it disabled, otherwise it silently completes.    You can literally make the triggers as involved as you would like to automate various things within the Companion software.  

Let me know if this helps your issue, or at least provides a usable work-around. If for some reason I misunderstood you issue, then please let me now. In all my use of the plugin it's connectivity to the Livestream software has been pretty solid, I don't think I've ever had the connection drop.   If your connection is randomly dropping out then we have other issues to work on with your config.  

Thanks,
C
